<?php

namespace Mb\UniversityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
	public function getFirstOrCreate($name,$em = null){

		if(!$em)
			$em =  $this->getEntityManager();
		
		$qb = $em->createQueryBuilder();
		$qb->select("c")
		->from('MbUniversityBundle:Country','c')
		->where('c.name = :c_name')
		->setParameter('c_name',$name);

		
		$country = $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();

		if($country == null){
			$country = new Country();
			$country-> setName($name);
			$em->persist($country);
		}


		return $country;

	}
}
