<?php

namespace Mb\UniversityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MobilityPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobilityPeriodRepository extends EntityRepository
{
	public function getFirst($type,$em = null){

		if(!$em)
			$em = $this->getEntityManager();
		
		$mobilityPeriod_type = (strtoupper($type));
		$qb = $em->createQueryBuilder();
		$qb->select("m")
		->from('MbUniversityBundle:MobilityPeriod','m')
		->where('m.type = :m_type')
		->setParameters(array('m_type'=>$mobilityPeriod_type));

		return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
	}
	
	public function getMbPeriod($type)
  {

    $stateNames = array( 'S7', 'S8', 'S9', 'Double Diplôme');
	 
    $qb= $this->createQueryBuilder('u');

	  $qb->where('u.type = :type')
			->setParameter('type',$stateNames[$type]);
	
    $query = $qb->getQuery();

    $results = $query->getResult();

    return $results[0];    // returns only a result
  }
}
