<?php

namespace Mb\UniversityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecificityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificityRepository extends EntityRepository
{
}
