imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']
    form_themes:
        - LexikFormFilterBundle:Form:form_div_layout.html.twig

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        default_entity_manager:  ~
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# FOS User Configuration
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Mb\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: false


# fr3d LDAP Bundle Configuration :
# driver, baseDn and ldap_attr names informations : given by the CRI, specific to the INSA LDAP
fr3d_ldap:
    driver:
       host:     ldap://ldap.insa-rennes.fr
       port:     389
    user:
        baseDn: ou=people,dc=insa-rennes,dc=fr
        filter: (&(ObjectClass=Person))
        attributes:
           - { ldap_attr: uid,  user_method: setUsername }
           - { ldap_attr: sn, user_method: setName }
           - { ldap_attr: givenname, user_method: setFirstName }
           - { ldap_attr: supannetuid, user_method: setStudentId }
           - { ldap_attr: mail, user_method: setEmail }
           - { ldap_attr: givename, user_method: setFirstName }
           - { ldap_attr: insaclasseetu, user_method: setYearStudy }
           - { ldap_attr: supannempid, user_method: setStudentId }
           - { ldap_attr: insapopulation, user_method: setYearStudy }
           #- { ldap_attr: , user_method: set }uidNumber
            # Can add some more, the ldap_attr shall be in lowercase
    service:
        ldap_manager:  mb.ldap.ldap_manager
        # Select the custom LDAP Manager in src/Mb/UserBundle/Ldap as the default LDAP Manager