mb_main:
    resource: "@MbMainBundle/Controller/"
    type:     annotation
    prefix:   /


mb_file:
    resource: "@MbFileBundle/Controller/"
    type:     annotation
    prefix:   /

mb_affect:
    resource: "@MbAffectBundle/Controller/"
    type:     annotation
    prefix:   /

mb_university:
    resource: "@MbUniversityBundle/Controller/"
    type:     annotation
    prefix:   /

mb_user:
    resource: "@MbUserBundle/Controller/"
    type:     annotation
    prefix:   /



login:
    path:   /login
    defaults:  { _controller: MbMainBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout
