security:
    encoders:
        Mb\UserBundle\Entity\User: sha512

    erase_credentials: false

    role_hierarchy:
        ROLE_SRI:       ROLE_STUDENT
        ROLE_ADMIN:       [ROLE_STUDENT, ROLE_SRI]
        ROLE_SUPER_ADMIN: [ROLE_STUDENT, ROLE_ADMIN, ROLE_SRI]

    # Informations given by FR3DLdapBundle github : https://github.com/Maks3w/FR3DLdapBundle
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            fr3d_ldap:  ~
            anonymous:      true
            provider:       fos_userbundle
            access_denied_url: /login
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     /
            remember_me:
                key:        %secret%


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/student, roles: ROLE_STUDENT }
        - { path: ^/supAdmin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }