<?php

namespace Mb\FileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileSendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileSendRepository extends EntityRepository
{
}
