<?php

namespace Mb\FileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * File_to_CompleteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class File_to_CompleteRepository extends EntityRepository
{
}
