<?php

namespace Mb\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends EntityRepository
{
	public function getFirst($name,$em){
		if($name == "tous dept")
			$name == "ALL";
		if(!$em)
			$em = $this->getDoctrine()->getManager();
		
		$department_name = (strtoupper($name));
		$qb = $em->createQueryBuilder();
		$qb->select("d")
		->from('MbMainBundle:Department','d')
		->where('d.name = :d_name')
		->setParameters(array('d_name'=>$department_name));

		return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
	}
	
	public function getDepartment($name)
  {

    $departmentNames = array(  'ALL', 'EII', 'GMA', 'INFO', 'GCU', 'GM', 'SRC', 'SGM');
	 
    $qb= $this->createQueryBuilder('u');

	  $qb->where('u.name = :name')
			->setParameter('name',$departmentNames[$name]);
	
    $query = $qb->getQuery();

    $results = $query->getResult();

    return $results[0];    // returns only a result
  }
	
}
