<?php

namespace Mb\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * YearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearRepository extends EntityRepository
{
	public function getCurrentYear(){
			
		$results = $this->findOneBy(
		  array (),
		  array('year' => 'DESC')
		);

		return $results;
		
	}
	
}
