<?php

namespace Mb\AffectBundle\Entity;

/**
 * AgreementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgreementRepository extends \Doctrine\ORM\EntityRepository
{
}
