<?php

namespace Mb\AffectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/*Récupère tout les voeux de l'année donné de l'utilisateur donnée par ordre de prioritée*/
/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends EntityRepository
{
    public function getWishesByOrdrer($user,$year){
		
        $qb= $this->createQueryBuilder('w');
		

		
        $qb->where('w.user = :user')
			->setParameter('user', $user)
			->andWhere('w.year = :year')
			->setParameter('year', $year);
			
        $qb->orderBy('w.priority', 'ASC');
		
        $query = $qb->getQuery();

        $results = $query->getResult();

        return $results;
    }

}

